name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request:
    name: Pull request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Run tests
        run: ./gradlew test
      - name: Build
        run: ./gradlew build