name: Release

on:
  push:
    tags: ['*']

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Get git tag
        uses: olegtarasov/get-tag@v2.1
      - name: Run tests
        run: ./gradlew test
      - name: Build
        run: ./gradlew build
      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ env.GIT_TAG_NAME }}'
          prerelease: false